# Generated by Django 5.0.6 on 2024-06-08 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("last_synced", models.DateTimeField(null=True)),
                ("last_block_number", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_hash",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("block_number", models.CharField(max_length=255)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("method", models.CharField(blank=True, max_length=255, null=True)),
                ("tx_type", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("gas_used", models.BigIntegerField()),
                ("priority_fee", models.BigIntegerField()),
                ("base_fee_per_gas", models.BigIntegerField()),
                (
                    "total_gas_paid",
                    models.DecimalField(decimal_places=5, max_digits=15),
                ),
                (
                    "error_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("revert_reason", models.TextField(blank=True, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_address",
                        to="address.address",
                    ),
                ),
                (
                    "from_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_transactions",
                        to="address.address",
                    ),
                ),
                (
                    "to_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_transactions",
                        to="address.address",
                    ),
                ),
            ],
        ),
    ]
