# Generated by Django 5.0.6 on 2024-06-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_hash', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_number', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('from_address', models.CharField(blank=True, max_length=255, null=True)),
                ('to_address', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('tx_type', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('gas_used', models.IntegerField()),
                ('priority_fee', models.IntegerField()),
                ('base_fee_per_gas', models.IntegerField()),
                ('total_gas_paid', models.IntegerField()),
                ('error_status', models.CharField(blank=True, max_length=255, null=True)),
                ('revert_reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
