# Generated by Django 5.0.6 on 2024-06-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0002_address_alter_transaction_base_fee_per_gas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="last_block_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="last_synced",
            field=models.DateTimeField(null=True),
        ),
    ]
