# Generated by Django 5.0.6 on 2024-06-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0002_transaction_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="block_number",
            field=models.BigIntegerField(),
        ),
    ]
