# Generated by Django 5.0.6 on 2024-06-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_alter_transaction_block_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="base_fee_per_gas",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="gas_used",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="priority_fee",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="total_gas_paid",
            field=models.BigIntegerField(),
        ),
    ]
