# Generated by Django 5.0.6 on 2024-06-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0004_alter_transaction_base_fee_per_gas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="base_fee_per_gas",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="block_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="gas_used",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="priority_fee",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="total_gas_paid",
            field=models.CharField(max_length=255),
        ),
    ]
