# Generated by Django 5.0.6 on 2024-06-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0005_alter_transaction_base_fee_per_gas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
