# Generated by Django 5.0.6 on 2024-06-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_alter_transaction_base_fee_per_gas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='total_gas_paid',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
