# Generated by Django 5.0.6 on 2024-06-08 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0006_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="from_address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_transactions",
                to="address.address",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_transactions",
                to="address.address",
            ),
        ),
    ]
