# Generated by Django 5.0.6 on 2024-06-08 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0007_alter_transaction_from_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_address",
                to="address.address",
            ),
        ),
    ]
